# Generated by Django 5.2.5 on 2025-10-10 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务描述')),
            ],
            options={
                'verbose_name': '任务类别',
                'verbose_name_plural': '任务类别',
                'db_table': 'db_task_category',
            },
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='用户名只能包含字母、数字和下划线', regex='^[a-zA-Z0-9_]+$')], verbose_name='用户名')),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='密码必须至少10位')], verbose_name='密码')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入有效的手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额')),
                ('english_level', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='英语水平')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'db_user_info',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Task1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('readingtext', models.TextField(verbose_name='阅读文本')),
                ('answertext1', models.TextField(verbose_name='答案1')),
                ('answertext2', models.TextField(verbose_name='答案2')),
                ('reasontext', models.TextField(verbose_name='解题思路')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task1_tasks', to='spoken_ai.taskcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '任务1',
                'verbose_name_plural': '任务1',
                'db_table': 'db_task1',
            },
        ),
    ]
