# Generated by Django 5.2.5 on 2025-10-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('readingtext', models.TextField(verbose_name='阅读文本（公告）')),
                ('audio', models.FileField(upload_to='task2_audio/', verbose_name='听力音频 (m4a)')),
                ('listeningtext', models.TextField(verbose_name='听力文本（学生观点）')),
                ('questiontext', models.TextField(verbose_name='问题')),
                ('answertext1', models.TextField(verbose_name='答案1')),
                ('answertext2', models.TextField(verbose_name='答案2')),
                ('reasontext', models.TextField(verbose_name='解题思路')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task2_tasks', to='spoken_ai.taskcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '任务2',
                'verbose_name_plural': '任务2',
                'db_table': 'db_task2',
            },
        ),
    ]
