# Generated by Django 5.2.5 on 2025-11-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0002_task2model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('readingtext', models.TextField(verbose_name='阅读文本（学术短文）')),
                ('audio', models.FileField(upload_to='task3_audio/', verbose_name='听力音频（课堂讲解/讲座，m4a）')),
                ('listeningtext', models.TextField(verbose_name='听力文本（课堂讲解/教授观点）')),
                ('questiontext', models.TextField(verbose_name='问题（Task 3 题目）')),
                ('answertext1', models.TextField(verbose_name='答案1（示例答案/高分范文1）')),
                ('answertext2', models.TextField(verbose_name='答案2（示例答案/高分范文2）')),
                ('reasontext', models.TextField(verbose_name='解题思路（答题要点与结构）')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task3_tasks', to='spoken_ai.taskcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '任务3',
                'verbose_name_plural': '任务3',
                'db_table': 'db_task3',
            },
        ),
    ]
