# Generated by Django 5.2.5 on 2025-11-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0003_task3model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task3Model',
        ),
    ]
