# Generated by Django 5.2.5 on 2025-11-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0005_task3model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('audio', models.FileField(upload_to='task4_audio/', verbose_name='听力音频（学术讲座，m4a）')),
                ('listeningtext', models.TextField(verbose_name='听力文本（讲座全文）')),
                ('questiontext', models.TextField(verbose_name='问题（Task 4 题目）')),
                ('answertext1', models.TextField(verbose_name='答案1（高分范文1）')),
                ('answertext2', models.TextField(verbose_name='答案2（高分范文2）')),
                ('reasontext', models.TextField(verbose_name='解题思路（答题结构与要点）')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task4_tasks', to='spoken_ai.taskcategory', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '任务4',
                'verbose_name_plural': '任务4',
                'db_table': 'db_task4',
            },
        ),
    ]
