# Generated by Django 5.2.5 on 2025-12-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0006_task4model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
