# Generated by Django 5.2.5 on 2026-01-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoken_ai', '0007_userinfomodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToeflRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Task 1 - Independent Speaking'), (2, 'Task 2 - Integrated Speaking'), (3, 'Task 3 - Integrated Academic'), (4, 'Task 4 - Academic Lecture')], verbose_name='任务类型')),
                ('student_answer', models.TextField(verbose_name='用户答案')),
                ('feedback', models.JSONField(blank=True, null=True, verbose_name='AI 反馈')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('score_details', models.JSONField(blank=True, null=True, verbose_name='详细评分')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='toefl_reports/%Y/%m/%d/', verbose_name='PDF 报告')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='toefl_audio/%Y/%m/%d/', verbose_name='音频文件')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('in_progress', '进行中'), ('reviewed', '已复习')], default='completed', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='用户备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_records_task1', to='spoken_ai.task1model', verbose_name='Task 1 题目')),
                ('task2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_records_task2', to='spoken_ai.task2model', verbose_name='Task 2 题目')),
                ('task3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_records_task3', to='spoken_ai.task3model', verbose_name='Task 3 题目')),
                ('task4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_records_task4', to='spoken_ai.task4model', verbose_name='Task 4 题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toefl_records', to='spoken_ai.userinfomodel', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'TOEFL 做题记录',
                'verbose_name_plural': 'TOEFL 做题记录',
                'db_table': 'db_toefl_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
