# Generated by Django 5.2.5 on 2025-12-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('spoken_ai', '0007_userinfomodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='房间名')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_forum_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(max_length=500, verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoken_ai.userinfomodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.forumroom')),
            ],
            options={
                'db_table': 'social_forum_message',
                'ordering': ['created_at'],
            },
        ),
    ]
