# Generated by Django 5.2.5 on 2026-01-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_postcomment'),
        ('spoken_ai', '0007_userinfomodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby_messages', to='spoken_ai.userinfomodel')),
            ],
            options={
                'db_table': 'social_lobby_message',
                'ordering': ['created_at'],
            },
        ),
    ]
